core/Home/urls.py
from django.urls import path
from .views import Home

app_name = 'Home'

urlpatterns = [
    path('', Home, name="Home"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cuentas/', include('cuentas.urls', namespace='cuentas')),
    path('Home/', include('Home.urls', namespace='Home')),
    path('vehiculos/', include('vehiculos.urls', namespace='vehiculos')),
]

# Para servir archivos en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/cuentas/urls.py
from django.urls import path
from .views import registro, loginView, api_registro, login_api, logoutView

app_name = 'cuentas'

urlpatterns = [
    path('registro/', registro, name='registro'),
    path('login/', loginView, name='login'),
    path('api_registro/', api_registro, name='api_registro'),
    path('api_login/', login_api, name='login_api'),
    path('logout/', logoutView, name='logout'),
]

core/cuentas/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    ROLES = [
        ('admin', 'Administrador'),
        ('guardia', 'Guardia'),
    ]
    cedula = models.CharField(max_length=10, unique=True, null=True)
    foto = models.ImageField(upload_to='cuentas/', null=True, blank=True)
    telefono = models.CharField(max_length=10, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    rol = models.CharField(max_length=20, choices=ROLES, default='guardia')

core/registros/models.py
from django.db import models
from vehiculos.models import Vehiculo
from cuentas.models import CustomUser

# Create your models here.
class TipoVisita(models.Model):
    nombre = models.CharField(max_length=70)

    def __str__(self):
        return self.nombre



class Empresa(models.Model):
    nombre = models.CharField(max_length=50)
    ruc = models.CharField(max_length=13)

    def __str__(self):
        return f'{self.nombre} - {self.ruc}'
    


class Garita(models.Model):
    nombre = models.CharField(max_length=25, unique=True)

    def __str__(self):
        return f'{self.nombre}'
    

class Lugar(models.Model):
    nombre = models.CharField(max_length=70)

    def __str__(self):
        return self.nombre

class Ruta(models.Model):
    lugar_partida = models.ForeignKey(Lugar, on_delete=models.CASCADE, related_name="ruta_partida")
    lugar_destino = models.ForeignKey(Lugar, on_delete=models.CASCADE, related_name="ruta_destino")

    def __str__(self):
        return f'Lugar de partida {self.lugar_partida} - Lugar de destino {self.lugar_destino}'

    
class Registro(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    ruta = models.ForeignKey(Ruta, on_delete=models.CASCADE)
    garita = models.ForeignKey(Garita, on_delete=models.CASCADE)
    guardia = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    fechaHoraIngreso = models.DateTimeField(auto_now_add=True)
    fechaHoraSalida = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'Vehiculo {self.vehiculo.placa} - Ruta {self.ruta} - {self.garita}'

core/cuentas/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django import forms
import os

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('foto', 'telefono', 'fecha_nacimiento', 'cedula', 'rol')
        
    def clean_cedula(self):
        cedula = (self.cleaned_data.get("cedula") or "").strip()
        if not cedula.isdigit() or len(cedula) != 10:
            raise forms.ValidationError('La cedula debe tener 10 digitos')
        return cedula
        
    def clean_telefono(self):
        telefono = (self.cleaned_data.get("telefono") or "").strip()
        if telefono and (not telefono.isdigit() or len(telefono) != 10):
            raise forms.ValidationError("El teléfono debe tener 10 dígitos.")
        return telefono

    def clean_foto(self):
        archivo = self.cleaned_data.get('foto')

        if not archivo:
            return archivo
        
        # Obtenemos el nombre del archivo (foto)
        nombre_archivo = archivo.name.lower().strip()

        # Obtenemos la extension
        extension = os.path.splitext(nombre_archivo)[1]
        extensiones_permitidas = ('.jpg', '.png', '.jpeg')

        if extension not in extensiones_permitidas:
            raise forms.ValidationError('Solo se permiten fotos en formato .png, .jpg o .jpeg')

        peso_maximo = 2 * 1024 * 1024
        if archivo.size > peso_maximo:
            raise forms.ValidationError('El peso maximo es de 2 MB')

        return archivo        
    

    def clean_fecha_nacimiento(self):
        fecha_nacimiento = self.cleaned_data.get('fecha_nacimiento')
        from datetime import date
        hoy = date.today()

        edad = hoy.year - fecha_nacimiento.year

        if (hoy.month, hoy.day) < (fecha_nacimiento.month, fecha_nacimiento.day):
            edad -= 1

        if edad < 18:
            raise forms.ValidationError('Debe tener minimo 18 años para registrarse')

        return fecha_nacimiento

core/cuentas/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.http import require_POST
from django.urls import reverse

# Create your views here.
def registro(request):
    form = CustomUserCreationForm()
    return render(request, 'registro.html', {'form':form})

@require_POST
def api_registro(request):
    form = CustomUserCreationForm(request.POST, request.FILES)
    if form.is_valid():
        user = form.save()
        return JsonResponse({
            'ok': True,
            'url' : reverse('cuentas:login')
        })
    else:
        return JsonResponse({
            'ok': False,
            'errors' : form.errors
        }, status = 400)



def loginView(request):
    return render(request, 'login.html')

@require_POST
def login_api(request):
    try:
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username = username, password = password)
        
        if user is None:
            return JsonResponse({
                'ok': False, 
                'errors': "Credenciales Invalidas"
            })
        
        return JsonResponse({
            'ok': True,
            "respuesta": "Inicio de sesion correcto",
            'url' : reverse('Home:Home')
        })
        
        
    except Exception as e:
        return JsonResponse({
            'ok': False,
            'errors': str(e)
        }, status=400)
        




def logoutView(request):
    logout(request)
    return redirect('cuentas:login')

core/registros/views.py
from django.shortcuts import render

# Create your views here.

core/cuentas/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Login</title>

  <!-- Solo define aquí la imagen del lado izquierdo -->
  <style>
    :root { --hero-url: url("{% static 'image/login.jpg' %}"); }
  </style>

  <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
  <main class="auth">
    <!-- ILUSTRACIÓN IZQUIERDA -->
    <section class="left">
      <div class="illustration" aria-label="login illustration"></div>
    </section>

    <!-- TARJETA DE LOGIN -->
    <section class="right">
      <div class="card">
        <h1>Welcome back</h1>
        <p class="subtitle">Inicia sesión para continuar</p>

        <!-- OAuth (opcional) -->
        <div class="oauth-row">
          <a href="#" class="btn oauth">
            <!-- Google -->
            <svg viewBox="0 0 48 48" class="icon" aria-hidden="true">
              <path fill="#FFC107" d="M43.6 20.1H42V20H24v8h11.3C33.6 31.9 29.2 35 24 35 16.8 35 11 29.2 11 22S16.8 9 24 9c3.6 0 6.9 1.4 9.3 3.6l5.7-5.7C35.6 3.1 30.1 1 24 1 10.7 1 0 11.7 0 25s10.7 24 24 24c12.4 0 23-9.1 23-24 0-1.6-.2-3.2-.4-4.9z"/>
              <path fill="#FF3D00" d="M6.3 14.7l6.6 4.8C14.4 16.2 18.9 13 24 13c3.6 0 6.9 1.4 9.3 3.6l5.7-5.7C35.6 3.1 30.1 1 24 1 16 1 9 5.3 6.3 14.7z"/>
              <path fill="#4CAF50" d="M24 49c6 0 11.5-2 15.6-5.4l-7.2-5.8C30 39.9 27.2 41 24 41c-5.2 0-9.6-3.1-11.3-7.4l-6.5 5C9 44.9 15.9 49 24 49z"/>
              <path fill="#1976D2" d="M43.6 20.1H42V20H24v8h11.3c-1.4 3.3-4.4 5.9-7.9 6.8l7.2 5.8C38.1 38 41 32.5 41 25c0-1.6-.2-3.2-.4-4.9z"/>
            </svg>
            <span>Continuar con Google</span>
          </a>

          <a href="#" class="btn oauth">
            <!-- GitHub -->
            <svg viewBox="0 0 24 24" class="icon" aria-hidden="true">
              <path fill="currentColor" d="M12 .5A12 12 0 0 0 8.2 23.9c.6.1.8-.26.8-.58v-2.02c-3.34.73-4.04-1.61-4.04-1.61-.55-1.38-1.33-1.75-1.33-1.75-1.09-.74.08-.73.08-.73 1.2.09 1.84 1.24 1.84 1.24 1.07 1.84 2.81 1.31 3.5 1 .11-.79.42-1.31.76-1.61-2.67-.3-5.47-1.33-5.47-5.93 0-1.31.47-2.38 1.24-3.22-.12-.3-.53-1.52.12-3.18 0 0 1.01-.32 3.3 1.23a11.5 11.5 0 0 1 6 0c2.29-1.55 3.3-1.23 3.3-1.23.65 1.66.24 2.88.12 3.18.77.84 1.24 1.91 1.24 3.22 0 4.6-2.8 5.63-5.48 5.93.43.37.81 1.1.81 2.22v3.29c0 .32.22.7.83.58A12 12 0 0 0 12 .5Z"/>
            </svg>
            <span>Continuar con GitHub</span>
          </a>
        </div>

        <div class="divider"><span>o con tu email</span></div>

        <!-- ERRORES DJANGO -->
        {% if form and form.errors %}
          <div class="errors">
            {% for field, errs in form.errors.items %}
              <p><b>{{ field|capfirst }}:</b> {{ errs|striptags }}</p>
            {% endfor %}
            {% for e in form.non_field_errors %}<p>{{ e }}</p>{% endfor %}
          </div>
        {% endif %}

        <!-- FORM -->
        <form class="form" method="post" id="form">
          {% csrf_token %}

          <div class="field">
            <label for="username">Correo o usuario</label>
            <input id="username" name="username" type="text" placeholder="tu@email.com"
                   required autocomplete="username">
            <p class="mensaje"></p>
          </div>

          <div class="field">
            <label for="password">Contraseña</label>
            <input id="password" name="password" type="password" placeholder="••••••••"
                   required autocomplete="current-password" minlength="8">
            <p class="mensaje"></p>
          </div>

          <div class="row">
            <label class="check">
              <input type="checkbox" name="remember"> <span>Recordarme</span>
            </label>
            <a class="link" href="#">¿Olvidaste tu contraseña?</a>
          </div>

          <button class="btn primary" type="submit">Iniciar sesión</button>
        </form>

        <p class="footnote">
          ¿No tienes cuenta?
          <a href="{% url 'cuentas:registro' %}" class="link">Crear cuenta</a>
        </p>
      </div>
    </section>
  </main>

  <script>
    window.URLS = {
        api_login: "{% url 'cuentas:login_api' %}"
    }
  </script>
  <script src="{% static 'js/login.js'  %}"></script>
</body>
</html>

core/cuentas/templates/registro.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Sign Up</title>
  <style>
  :root {
    --hero-url: url("{% static 'image/registro.png' %}");
  }
</style>
  <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>
<body>
  <main class="auth">
    <!-- LADO IZQUIERDO (ilustración) -->
    <section class="left">
      <div class="illustration" aria-label="signup illustration"></div>
    </section>

    <!-- LADO DERECHO (formulario) -->
    <section class="right">
      <div class="card">
        <h1>Sign Up</h1>
        <p class="subtitle">Únete a la comunidad con acceso permanente y gratis</p>


        <!-- ERRORES DEL FORM -->
        <div class="errors" id="form-errors"></div>
            

        <!-- FORMULARIO DJANGO -->
        <form class="form" method="post" enctype="multipart/form-data" autocomplete="on" id="form">
          {% csrf_token %}

          <div class="grid-2">
            <div class="field">
              <label for="first_name">Nombres</label>
              <input id="first_name" name="first_name" type="text" placeholder="Luis" maxlength="150" autocomplete="given-name">
                <p class="mensaje"></p>
            </div>
            <div class="field">
              <label for="last_name">Apellidos</label>
              <input id="last_name" name="last_name" type="text" placeholder="Suarez" maxlength="150" autocomplete="family-name">
                <p class="mensaje"></p>
            </div>
          </div>

          <div class="field">
            <label for="username">Usuario <span>*</span></label>
            <input id="username" name="username" type="text" placeholder="tu_usuario" required maxlength="150" autocomplete="username">
            <p class="mensaje"></p>
          </div>

          <div class="field">
            <label for="email">Correo <span>*</span></label>
            <input id="email" name="email" type="email" placeholder="correo@dominio.com" required autocomplete="email">
            <p class="mensaje"></p>
          </div>

          <div class="grid-2">
            <div class="field">
              <label for="password1">Contraseña <span>*</span></label>
                <input id="password1" name="password1" type="password" placeholder="Mín. 8 caracteres" required autocomplete="new-password" minlength="8">
                <p class="mensaje"></p>
            </div>
            <div class="field">
              <label for="password2">Repetir contraseña <span>*</span></label>
                <input id="password2" name="password2" type="password" placeholder="Mín. 8 caracteres" required autocomplete="new-password" minlength="8">
                <p class="mensaje"></p>
            </div>
          </div>

          <div class="grid-2">
            <div class="field">
              <label for="cedula">Cedula</label>
              <input id="cedula" name="cedula" type="text" inputmode="numeric" pattern="[0-9]{10}" maxlength="10" placeholder="0954234548">
              <p class="mensaje"></p>
            </div>
            <div class="field">
              <label for="telefono">Teléfono</label>
              <input id="telefono" name="telefono" type="text" inputmode="numeric" pattern="[0-9]{10}" maxlength="10" placeholder="0999999999" autocomplete="tel">
              <p class="mensaje"></p>
            </div>
          </div>

          <div class="field">
            <label for="fecha_nacimiento">Fecha de nacimiento</label>
            <input id="fecha_nacimiento" name="fecha_nacimiento" type="date" max="2099-12-31">
            <p class="mensaje"></p>
          </div>

          <div class="field">
            <label>Rol</label>
            <select name="rol" required>
              <option value="guardia">Guardia</option>
              <option value="admin">Administrador</option>
            </select>
          </div>

          <div class="field">
            <label for="foto">Foto (opcional)</label>
            <input id="foto" name="foto" type="file" accept="image/*">
            <div class="preview" id="preview"></div>
          </div>

          <button type="submit" class="btn primary">Crear cuenta</button>
        </form>

        <p class="footnote">
          ¿Ya tienes cuenta?
          <a href="{% url 'cuentas:login' %}" class="link">Login here</a>
        </p>
      </div>
    </section>
  </main>

  <script>
    window.URLS = {
        api_registro: "{% url 'cuentas:api_registro' %}"
    }
  </script>
  <script src="{% static 'js/validaciones.js'  %}"></script>
  <script src="{% static 'js/registro.js'  %}"></script>
</body>
</html>